### ISSUE TITLE
Index error when processing data?

### ISSUE THREAD

**Issue by lizard-heart** [carykh/AbacabaCOVID19#2]
Hi, I tried the Gapminder Inspired one and when I run processData.py, I get the following error:

```
Traceback (most recent call last):
  File "processdata.py", line 97, in <module>
    cases_str = getStr("Daily New Cases in",name)
  File "processdata.py", line 64, in getStr
    data_1[day] = strToInt(array_1[i])
IndexError: index 538 is out of bounds for axis 0 with size 538
```

I tried to fix it myself, but I wasn't able to.

**Comment by Khosraw** [comment]
> Hi, I tried the Gapminder Inspired one and when I run processData.py, I get the following error:
> 
> ```
> Traceback (most recent call last):
>   File "processdata.py", line 97, in <module>
>     cases_str = getStr("Daily New Cases in",name)
>   File "processdata.py", line 64, in getStr
>     data_1[day] = strToInt(array_1[i])
> IndexError: index 538 is out of bounds for axis 0 with size 538
> ```
> 
> I tried to fix it myself, but I wasn't able to.

An index out of bounds error is when an index value provided doesn't exist within the array's range. To fix this, you just have to change `DAY_LEN` variable in line 6 to whatever day your data ends. For example, if the data ends on June 26th, 2021, that variable should be set to 543.

**Comment by carykh** [comment]
@Khosraw  is correct, you have to set DAY_LEN to the number of days between Jan 1, 2020 and the most recent date of the dataset.

HOWEVER, 2 minutes ago, I modified the code to figure out DAY_LEN from the webpages themselves, so you don't need to worry about that anymore. @lizard-heart , if you download the latest version of the repo, and run getData.py and processData.py, it should work fine even if you don't set DAY_LEN yourself! 😃

**Comment by Khosraw** [comment]
Thanks for the change. I will also pull the repository for that update.

**Comment by lizard-heart** [comment]
Got it, I changed day_len and it worked.

**Comment by iamthewallrus** [comment]
Close the report then.

**Comment by carykh** [comment]
Oh right, thanks for reminding me @iamthewallrus! I was going to close it within a few days of making that update, so people who'd downloaded the original version could have time to see that the issue and its fix were still there. But of course, people can see closed issues, after all! So I'll close it now.
